### ISSUE TITLE
Code licence

### ISSUE THREAD

**Issue by tkipf** [ermongroup/graphite#2]
Thanks for releasing your code of Graphite! 

I noticed that your code is largely based on a fork of https://github.com/tkipf/gae and I would greatly appreciate attribution where code was copied (please consider placing a reference in each function header where code was copied). Please also consider following the licence of the original code release: https://github.com/tkipf/gae/blob/master/LICENCE

Thanks!

**Comment by tkipf** [comment]
@aditya-grover

**Comment by aditya-grover** [comment]
Sure, thanks for bringing this to our attention! We'll post a revision to the source files in the next few days. For now, I have added a link to the GAE repo within the README.

**Comment by tkipf** [comment]
Awesome, thanks!
